vich_uploader:
    db_driver: orm

    mappings:
        product_thumb:
            uri_prefix: /thumbs
            upload_destination: '%kernel.project_dir%/public/thumbs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer 
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
